Chatbot/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name='landing'),
    path('',include('Chatbotapp.urls')),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Chatbotapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'Chatbotapp'

urlpatterns = [
     path('home',views.home,name='home'),
     path('getResponse',views.getResponse,name='getResponse')
]

Chatbotapp/models.py
from django.db import models

# Create your models here.

Chatbot/views.py
from django.shortcuts import render


def landing(request):
    return render(request,'landing.html')

Chatbotapp/views.py
# from django.shortcuts import render
# from django.http import HttpResponse

# # Create your views here.

# from chatterbot import ChatBot
# from chatterbot.trainers import ListTrainer

# bot=ChatBot('chatbot' ,read_only=False,
# logic_adapters=[
#     {
#        'import_path':'chatterbot.logic.BestMatch',
#         'default_response':'Sorry,I dont know what that means',  
#         'maximum_similarity_threshold':0.90,

#     }
#     ])

# conversation = [
#     "Hello",
#     "Hi there!",
#     "How are you doing?",
#     "I'm doing great.",
#     "That is good to hear",
#     "Thank you.",
#     "You're welcome."
# ]

# trainer = ListTrainer(bot)
# trainer.train(conversation)

# # trainer = ChatterBotCorpusTrainer(bot)
# # trainer.train('chatterbot.corpus.english')

from django.shortcuts import render
from django.http import HttpResponse
import openai
from llama_index.core import VectorStoreIndex,SimpleDirectoryReader,ServiceContext,PromptTemplate, Document
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings
import openai


openai.api_key = "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"

def read_data():
    
  reader =SimpleDirectoryReader(input_dir=r"/home/sanchit/San/mini/mini project/data", recursive=True)
  docs = reader.load_data()

  service_context = ServiceContext.from_defaults(llm=OpenAI(model="gpt-3.5-turbo", temperature=0.5, system_prompt="You are an expert on the docs and can provide helpful summaries"))
  index = VectorStoreIndex.from_documents(docs, service_context=service_context)
  chat_engine = index.as_chat_engine(chat_mode="condense_question", verbose=True)
  return chat_engine

chat_engine = read_data()
prompt ="""Summarize the main points and key information from the provided PDF document.
 The document covers [brief description of the content]. Please generate a concise summary of approximately 3-4 sentences. """
response = chat_engine.chat(prompt)
print(response.response)



# def chatbot_view(request):
#     if request.method == 'POST':
#         chat_engine = read_data()
#         prompt = request.POST.get('prompt', '')
#         response = chat_engine.chat(prompt)
#         print(response)
#         return render(request, 'chatbot.html', {'prompt': prompt, 'response': response})
#     else:
#         return render(request, 'chatbot.html', {})



def home(request):
    return render(request,'home.html')


def getResponse(request):
    chat_engine = read_data()
    usermessage=request.GET.get('userMessage')
    response = chat_engine.chat(usermessage)
    # response = str(bot.get_response(usermessage))
    print(response)
    return HttpResponse(response)

Chatbotapp/templates/home.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chatbot</title>

    <!-- vendor css & style files -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300|Open+Sans:300|Oxygen|Material+Icons"
        rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- <link rel="stylesheet" href="{% static 'css/particle.css' %}"> -->


    <script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</head>

<body>

    <!-- <h1> Chatbot App </h1> -->
    <!-- <div>
        <div id="chatbot">
            <p class="botText"><span>Hii There </span></p>
        </div>
        <div id="userinput">
            <input type="text" name="userMessage" id="textInput" placeholder="Type your message ">
            <input type="submit" value="Send" id="buttoninput">
        </div>
    </div> -->


    <div class="container" style="margin-top: 5%;">

        <div class="row padded_row">

            <div id="chat-text-area" class="col-md-7 chat-text-area">

                <div class="chat_window">

                    <div class="top_menu">
                        <div class="title">ChatBot - IIIT Lucknow </div>
                    </div>

                    <ul class="messages"></ul>
                    <div class="bottom_wrapper">
                        <input id="msg_input" placeholder="Say Hi to begin chat..." />
                        <div id="send_button" class="app_button_1">Send</div>
                    </div>

                </div>

            </div>


        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

    <div>
    
      
    
    
    <div>
      
      
    

    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    </script>


    <!-- <script>
        function getUserResponse() {

            var userText = $('#textInput').val();
            var userHTML = "<p class='userText'> User: <span>" + userText + "</span></p>";
            $('#textInput').val("");
            $('#chatbot').append(userHTML);

            $.get('../getResponse', { userMessage: userText }).done(function (data) {
                var returnedMessage = "<p class='botText'> Chatbot: <span>" + data + "</span></p>";
                $('#chatbot').append(returnedMessage);
            })
        }
        $('#buttoninput').click(function () {
            getUserResponse();
        })

    </script> -->

    <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">
    {% block custom_css %}{% endblock custom_css %}
    <title>IIITL College ChatBot
    </title>
    <link rel="shortcut icon" type="image/png" href="assets/favicon.png">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <!-- <script type='text/javascript' src='js/jquery-1.11.1.min.js'></script> -->
    <script type="text/javascript" src="{% static 'js/jquery.particleground.js' %}"></script>
</head>

<body>
    {% comment %} {% include 'navbar.html' %} {% endcomment %}
    
    {% block content %}
    
    {% endblock content %}
    
    
    <!-- All javascript files goes under here    -->
    {% block custom_js %}{% endblock custom_js %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>

    
</body>

</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block custom_css %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/particle.css' %}">

{% endblock custom_css %}

{% block content %}

<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

<div>
<article id="info">
 
<div id="particles-js"></div>

</div>

<header>
 <div class="stars"></div>
<div class="twinkle"></div>
</header>

<div id="intro">
  <div id="mainText">
    <h1 id="DelvinText">Delvin</h1>
    <p style="color: azure;" >
      <b>
        The IIIT Lucknow chatbot is an AI-driven assistant providing information about IIIT Lucknow, assisting with admissions, courses, and events. It offers personalized support and quick access to FAQs, enhancing communication and accessibility.</p>  
      </b>
  </div>
  <div class="wrapper">
    <div class="link_wrapper">
      <a href="{% url 'Chatbotapp:home' %}"><span>Let's get </span>started</a>
      <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 268.832 268.832">
          <path d="M265.17 125.577l-80-80c-4.88-4.88-12.796-4.88-17.677 0-4.882 4.882-4.882 12.796 0 17.678l58.66 58.66H12.5c-6.903 0-12.5 5.598-12.5 12.5 0 6.903 5.597 12.5 12.5 12.5h213.654l-58.66 58.662c-4.88 4.882-4.88 12.796 0 17.678 2.44 2.44 5.64 3.66 8.84 3.66s6.398-1.22 8.84-3.66l79.997-80c4.883-4.882 4.883-12.796 0-17.678z"/>
        </svg>
      </div>
    </div>
    
  </div>
</div>
 
{% comment %} <div id="particles">
    <div id="intro">
      <div id="mainText">
        <h1 id="DelvinText">Delvin</h1>
        <p style="color: azure;" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus placeat voluptate sunt eius dicta fugiat magni maiores? Debitis ab quae ea, vero aspernatur qui dolorum accusamus. Minus reprehenderit ducimus atque, praesentium ratione voluptate provident harum exercitationem dignissimos aspernatur temporibus</p>  
      </div>
      <div class="wrapper">
        <div class="link_wrapper">
          <a href="{% url 'Chatbotapp:home' %}"><p>Let's get </p>started</a>
          <div class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 268.832 268.832">
              <path d="M265.17 125.577l-80-80c-4.88-4.88-12.796-4.88-17.677 0-4.882 4.882-4.882 12.796 0 17.678l58.66 58.66H12.5c-6.903 0-12.5 5.598-12.5 12.5 0 6.903 5.597 12.5 12.5 12.5h213.654l-58.66 58.662c-4.88 4.882-4.88 12.796 0 17.678 2.44 2.44 5.64 3.66 8.84 3.66s6.398-1.22 8.84-3.66l79.997-80c4.883-4.882 4.883-12.796 0-17.678z"/>
            </svg>
          </div>
        </div>
        
      </div>
    </div>
  </div> {% endcomment %}


</article>
  


<div>
  
  


{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light mb-5">
    <a class="navbar-brand" href="{% url 'landing' %}"><i class="fas fa-person-booth"></i></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'landing' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% comment %} <a class="nav-link" href="{% url 'feedback:contact' %}">Contact Us</a> {% endcomment %}
            </li>
        </ul>
        <div class="navbar-nav ml-auto">
            <a class="nav-link" href="{% url 'Chatbotapp:home' %}">ChatBot</a>

         
        </div>
    </div>
</nav>